[package]
name = "acril-rt"
version = "0.1.0"
edition = "2021"

[dependencies]
acril = { git = "https://github.com/PassivityTrading/acril", version = "0.1.0", default-features = false }
tokio = { version = "1.35.1", features = ["rt", "sync", "macros"] }
